apiVersion: v1
kind: Service
metadata:
  labels:
    app: geth-rinkeby-node
  name: geth-rinkeby-node
spec:
  ports:
  - name: discovery
    port: 30303
    protocol: TCP
    targetPort: 30303
  - name: rpc
    port: 8545
    protocol: TCP
    targetPort: 8545
  - name: ws
    port: 8546
    protocol: TCP
    targetPort: 8546
  selector:
    app: geth-rinkeby-node
    tier: geth-rinkeby-node
  sessionAffinity: None
  clusterIP: 10.55.249.202