apiVersion: v1
kind: Service
metadata:
  labels:
    app: geth-node
  name: geth-node
spec:
  ports:
  - name: discovery
    port: 30303
    protocol: TCP
    targetPort: 30303
  - name: rpc
    port: 8545
    protocol: TCP
    targetPort: 8545
  - name: ws
    port: 8546
    protocol: TCP
    targetPort: 8546
  selector:
    app: geth-node
    tier: geth-node
  sessionAffinity: None
  type: LoadBalancer