apiVersion: v1
kind: PersistentVolume
metadata:
  name: cent-0-pv
spec:
  storageClassName: ""
  capacity:
    storage: 100G
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  gcePersistentDisk:
    pdName: cent-0-pd
    fsType: ext4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cent-0-pvc
spec:
  storageClassName: ""
  volumeName: cent-0-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100G