# Type of the label that notes a kind of each lines.
labelType: long

# Style of "Build" lines.
buildStyle:
  # Hide lines
  hide: false
  # Bold or increased intensity.
  bold: true
  faint: 
  italic: 
  underline: 
  blinkSlow: 
  blinkRapid: 
  # Swap the foreground color and background color.
  inverse: true
  conceal: 
  crossOut: 
  frame: 
  encircle: 
  overline: 
  # Fore-color of text
  foreground: rgb(23,34,122)
  # Back-color of text
  background: # Same format as `foreground`

# Style of the "Start" lines.
startStyle:
# Same format as `buildStyle`

# Style of the "Pass" lines.
passStyle:
# Same format as `buildStyle`

# Style of the "Fail" lines.
failStyle:
# Same format as `buildStyle`

# Style of the "Skip" lines.
skipStyle:
# Same format as `buildStyle`

# Style of the "File" lines.
fileStyle:
# Same format as `buildStyle`

# Style of the "Line" lines.
lineStyle:
# Same format as `buildStyle`

# A threashold of the coverage
coverThreshold: 30

# Style of the "Cover" lines with the coverage that is higher than coverThreshold.
coveredStyle:
# Same format as `buildStyle`

# Style of the "Cover" lines with the coverage that is lower than coverThreshold.
uncoveredStyle:
# Same format as `buildStyle`

# If you want to delete lines, write the regular expressions.
removals:
- (regexp)