language: go
go:
  - 1.7.x

cache:  
    directories:    
      - $GOPATH/pkg/dep  
      # use a separate depbin to allow for caching
      - $GOPATH/pkg/depbin 
      # cache the etherum go code so don't have to get each time
      - $GOPATH/src/github.com/ethereum

install:
  - build/install-dependencies.sh
  - dep ensure
  - rm -rf vendor/github.com/ethereum


script:  go test $(go list ./... | grep -v /vendor/)
