language: go
go:
  - 1.9.x

cache:  
    directories:
      # Cache the glide binary
      - ~/glide/
      # Glide's own cache
      - ~/.glide
      # Use a separate depbin folder to allow for caching. 
      # The bin itself is then linked (ln -s) in the install-dependencies script
      - $GOPATH/pkg/depbin 

install:
  - scripts/install-dependencies.sh
  - glide install
  - cd vendor/github.com/golang/protobuf && make install
  - go get -u github.com/grpc-ecosystem/grpc-gateway/protoc-gen-grpc-gateway
  - go get -u github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger

# Exclude the vendor dir from test run. 
# The test runner included it on travis if not explicitly excluded.
script:  echo `pwd` && ls && go test ./centrifuge/...
