language: go
go:
  - 1.7.x

cache:  
    directories:    
      - $GOPATH/pkg/dep  
      # use a separate depbin to allow for caching
      - $GOPATH/pkg/depbin 

install:
  - build/install-dependencies.sh
  - go get github.com/ethereum/go-ethereum
  - dep ensure
  - rm -rf vendor/github.com/ethereum

# exclude the vendor dir from test run. 
# the test runner included it on travis if not explicitly excluded
script:  go test $(go list ./... | grep -v /vendor/)
