language: go
go:
  - 1.9.x
node_js:
  - "8"

env:
  - RUN_CONTEXT=travis

cache:  
    directories:
      # Cache the glide binary
      - ~/glide/
      # Glide's own cache
      - ~/.glide
      # Use a separate depbin folder to allow for caching. 
      # The bin itself is then linked (ln -s) in the install-dependencies script
      - $GOPATH/pkg/depbin
      # Cache DAG data
      - /tmp/geth_test_network/.ethash

before_install:
  - npm install -g truffle@4.0.4

install:
  - scripts/install-dependencies.sh
  - glide install
  - mkdir -p /tmp/geth_bin
  - wget https://gethstore.blob.core.windows.net/builds/geth-linux-amd64-1.8.2-b8b9f7f4.tar.gz -P /tmp/geth_bin
  - tar -xzvf /tmp/geth_bin/geth-linux-amd64-1.8.2-b8b9f7f4.tar.gz -C /tmp/geth_bin/
  - export PATH=$PATH:/tmp/geth_bin/geth-linux-amd64-1.8.2-b8b9f7f4/
  - echo "cd vendor/github.com/golang/protobuf && make install" | sh
  - go get -u github.com/grpc-ecosystem/grpc-gateway/protoc-gen-grpc-gateway
  - go get -u github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger
  - git clone git@github.com:CentrifugeInc/centrifuge-ethereum-contracts.git $GOPATH/src/github.com/CentrifugeInc/centrifuge-ethereum-contracts

script: true
