language: go
go:
  - 1.11.4

# Maybe this helps with building branches in a fork
go_import_path: github.com/centrifuge/go-centrifuge

services:
  - docker

env:
  matrix:
    - DEPCACHEDIR=/tmp/depcache IMAGE_NAME=centrifugeio/go-centrifuge

checkout:
  post:
    git pull --ff-only origin "refs/pull/${CI_PULL_REQUEST//*pull\//}/merge"

cache:
  directories:
    - ~/bin/
    - /tmp/depcache

before_install:
  - nvm install 10.15.1
  - npm install -g truffle@4.1.13

install:
  - mkdir -p ~/bin
  - go get -u github.com/kyoh86/richgo
  - make install

jobs:
  include:
    - stage: "Tests"
      name: "Linting"
      script:
        - make lint-check gen-swagger generate format-go
        - echo "Checking that prototool and format-go don't result in a modified git tree" && git diff --exit-code protobufs/gen
    - stage: "Tests"
      name: "Unit and CMD tests"
      script:
        - ./build/scripts/test_wrapper.sh unit cmd
      after_success:
        - bash <(curl -s https://codecov.io/bash)
    - stage: "Tests"
      name: "Integration tests"
      script:
        - ./build/scripts/test_wrapper.sh integration
      after_success:
        - bash <(curl -s https://codecov.io/bash)
    - stage: "Tests"
      name: "Test world tests"
      script:
        - ./build/scripts/test_wrapper.sh testworld
      after_success:
        - bash <(curl -s https://codecov.io/bash)
    - stage: build_artifacts
      if: (NOT type IN (pull_request)) AND ((branch = develop) OR (branch = master))
      before_script:
       - touch ./build/peak-vista-185616-9f70002df7eb.json.enc
       - echo $CREDENTIALS_GCP | base64 -d > ./build/peak-vista-185616-9f70002df7eb.json.enc
       - openssl aes-256-cbc -K $encrypted_f84a564476a2_key -iv $encrypted_f84a564476a2_iv -in ./build/peak-vista-185616-9f70002df7eb.json.enc -out ./build/peak-vista-185616-9f70002df7eb.json -d
      script: make build-ci
      after_script:
       - ./build/scripts/push_to_swagger.sh
