language: go
go:
  - 1.9.x

services:
  - docker

env:
  - RUN_CONTEXT=travis
  - GETH_DOCKER_VERSION=v1.8.1

cache:
    directories:
      # Cache the glide binary
      - ~/glide/
      # Glide's own cache
      - ~/.glide
      # Use a separate depbin folder to allow for caching. 
      # The bin itself is then linked (ln -s) in the install-dependencies script
      - $GOPATH/pkg/depbin
      # Cache DAG data
      - /tmp/geth_test_network/.ethash

before_install:
  - npm install -g truffle@4.0.4
  - docker pull ethereum/client-go:$GETH_DOCKER_VERSION

install:
  - scripts/install-dependencies.sh
  - glide install
  - echo "cd vendor/github.com/golang/protobuf && make install" | sh
  - go get -u github.com/grpc-ecosystem/grpc-gateway/protoc-gen-grpc-gateway
  - go get -u github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger
  - git clone git@github.com:CentrifugeInc/centrifuge-ethereum-contracts.git $GOPATH/src/github.com/CentrifugeInc/centrifuge-ethereum-contracts

script:
  - scripts/test_wrapper.sh
