language: go
go:
  - 1.10.x

# Maybe this helps with building branches in a fork
go_import_path: github.com/CentrifugeInc/go-centrifuge
services:
  - docker

env:
  - RUN_CONTEXT=travis DEPCACHEDIR=/tmp/depcache
cache:
      # Cache DAG data
      - /tmp/geth_test_network/.ethash
      - /tmp/depcache

before_install:
  - npm install -g truffle@4.0.4
install:
  - go get -u github.com/golang/dep/...
  - dep ensure


script:
  - scripts/test_wrapper.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
