language: go
go:
  - master

env:
  - DEP_VERSION="0.4.1"

cache:  
    directories:    
      - $GOPATH/pkg/dep  
      - $GOPATH/bin/dep     

before_install:
  # Download the binary to bin folder in $GOPATH
  - curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o $GOPATH/bin/dep
  # Make the binary executable
  - chmod +x $GOPATH/bin/dep


install:
  - go get github.com/ethereum/go-ethereum
  - dep ensure
  - rm -rf vendor/github.com/ethereum


script:  go test ./...
