ignore:
  - identity/ideth/factory_contract.go
  - identity/ideth/identity_contract.go
  - anchors/anchor_contract.go
  - nft/invoice_unpaid_contract.go
  - documents/entity/test_entity.go
  - documents/invoice/test_invoice.go
  - migrations/files
  - testworld