ignore:
  - identity/ideth/factory_contract.go
  - identity/ideth/identity_contract.go
  - "**/mocks.go"
  - migrations/files
  - testworld
  - build
  - resources
  - testingutils
  - errors/stack.go
