centrifugeNetwork: russianhill
networks:
  # Local testing contract addresses need to be set with env variables.
  testing:
    id: 333
    ethereumNetworkId: 8383
    bootstrapPeers:
      - "/ip4/127.0.0.1/tcp/38202/ipfs/QmTQxbwkuZYYDfuzTbxEAReTNCLozyy558vQngVvPMjLYk"
      - "/ip4/127.0.0.1/tcp/38203/ipfs/QmVf6EN6mkqWejWKW2qPu16XpdG3kJo1T3mhahPB5Se5n1"
    contractAddresses:
      identityFactory: ""
      identityRegistry: ""
      anchorRepository: ""
      paymentObligation: ""

  russianhill:
    id: 51
    bootstrapPeers:
      - "/ip4/35.225.200.42/tcp/38202/ipfs/12D3KooWLiicQVwThTBY6xKcPoLf6RQYJFpwf1r75wLx2ZR3pCd1"
      - "/ip4/35.225.86.210/tcp/38202/ipfs/12D3KooWQZMA8GPHrvEZB9wdkoUcAAmCZHp9eyyZ4SE8gFr3hTNX"

    ethereumNetworkId: 4
    contractAddresses: 
      identityFactory: "0x90d294571e73842697a66b7a99a09dd6c73d356d"
      identityRegistry: "0x9660c039d311453af0d58c5666723d9c2fa7d6ec"
      anchorRepository: "0x7f854dfa98012d7fa55c803bba2260bcdee4b5ed"
      paymentObligation: ""

queue:
  numWorkers: 2
  workerWaitTimeMS: 1

ethereum:
  defaultAccountName: "main"
  nodeURL: ws://localhost:9546
  gasPrice: 1000000000
  gasLimit: 4712388
  contextWaitTimeout: "600s"
  maxRetries: 200
  intervalRetry: "2s"
  txPoolAccessEnabled: true

