on:
  release:
    types: [created]
name: Release
jobs:
  build:
    strategy:
      matrix:
        go-version: [1.15.x]
        os: [ubuntu-latest, macos-latest]
        arch: [amd64]
    runs-on: ${{ matrix.os }}
    env:
      GOPATH: ${{ github.workspace }}
    defaults:
      run:
        working-directory: ${{ env.GOPATH }}/src/github.com/${{ github.repository }}
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Check out code
        uses: actions/checkout@v2
        with:
          path: ${{ env.GOPATH }}/src/github.com/${{ github.repository }}
          fetch-depth: 0
      - uses: actions/cache@v2
        with:
          path: ${{ env.GOPATH }}/pkg/mod
          key: ${{ runner.os }}-go-${{ github.job }}-${{ matrix.arch }}
      - name: Build ${{ matrix.os }}-${{ matrix.arch }} binary
        run: arch=${{ matrix.arch }} make build-binary
      - name: Push artifacts
        run: make upload-artifacts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          INPUT_ARGS: "*.tar.gz"
